/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ERC8004Registry {
  export type AgentIdentityStruct = {
    active: boolean;
    agentType: string;
    metadataURI: string;
    owner: AddressLike;
    registeredAt: BigNumberish;
  };

  export type AgentIdentityStructOutput = [
    active: boolean,
    agentType: string,
    metadataURI: string,
    owner: string,
    registeredAt: bigint
  ] & {
    active: boolean;
    agentType: string;
    metadataURI: string;
    owner: string;
    registeredAt: bigint;
  };

  export type ReputationRecordStruct = {
    score: BigNumberish;
    tradeCount: BigNumberish;
    lastUpdatedAt: BigNumberish;
  };

  export type ReputationRecordStructOutput = [
    score: bigint,
    tradeCount: bigint,
    lastUpdatedAt: bigint
  ] & { score: bigint; tradeCount: bigint; lastUpdatedAt: bigint };
}

export interface ERC8004RegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "atomicSwapContract"
      | "deployer"
      | "deregisterAgent"
      | "getIdentity"
      | "getRegisteredAgents"
      | "getReputation"
      | "incrementReputation"
      | "registerAgent"
      | "setAtomicSwapContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeregistered"
      | "AgentRegistered"
      | "ReputationIncremented"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "atomicSwapContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deregisterAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementReputation",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAtomicSwapContract",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "atomicSwapContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deregisterAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAtomicSwapContract",
    data: BytesLike
  ): Result;
}

export namespace AgentDeregisteredEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    agentType: string,
    metadataURI: string
  ];
  export type OutputTuple = [
    agent: string,
    agentType: string,
    metadataURI: string
  ];
  export interface OutputObject {
    agent: string;
    agentType: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationIncrementedEvent {
  export type InputTuple = [
    agent: AddressLike,
    delta: BigNumberish,
    newScore: BigNumberish,
    tradeRef: BytesLike
  ];
  export type OutputTuple = [
    agent: string,
    delta: bigint,
    newScore: bigint,
    tradeRef: string
  ];
  export interface OutputObject {
    agent: string;
    delta: bigint;
    newScore: bigint;
    tradeRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC8004Registry extends BaseContract {
  connect(runner?: ContractRunner | null): ERC8004Registry;
  waitForDeployment(): Promise<this>;

  interface: ERC8004RegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  atomicSwapContract: TypedContractMethod<[], [string], "view">;

  deployer: TypedContractMethod<[], [string], "view">;

  deregisterAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  getIdentity: TypedContractMethod<
    [agent: AddressLike],
    [ERC8004Registry.AgentIdentityStructOutput],
    "view"
  >;

  getRegisteredAgents: TypedContractMethod<[], [string[]], "view">;

  getReputation: TypedContractMethod<
    [agent: AddressLike],
    [ERC8004Registry.ReputationRecordStructOutput],
    "view"
  >;

  incrementReputation: TypedContractMethod<
    [agent: AddressLike, delta: BigNumberish, tradeRef: BytesLike],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [agent: AddressLike, agentType: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  setAtomicSwapContract: TypedContractMethod<
    [_atomicSwap: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "atomicSwapContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deregisterAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIdentity"
  ): TypedContractMethod<
    [agent: AddressLike],
    [ERC8004Registry.AgentIdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [agent: AddressLike],
    [ERC8004Registry.ReputationRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "incrementReputation"
  ): TypedContractMethod<
    [agent: AddressLike, delta: BigNumberish, tradeRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agent: AddressLike, agentType: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAtomicSwapContract"
  ): TypedContractMethod<[_atomicSwap: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentDeregistered"
  ): TypedContractEvent<
    AgentDeregisteredEvent.InputTuple,
    AgentDeregisteredEvent.OutputTuple,
    AgentDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationIncremented"
  ): TypedContractEvent<
    ReputationIncrementedEvent.InputTuple,
    ReputationIncrementedEvent.OutputTuple,
    ReputationIncrementedEvent.OutputObject
  >;

  filters: {
    "AgentDeregistered(address)": TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;
    AgentDeregistered: TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;

    "AgentRegistered(address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "ReputationIncremented(address,uint256,uint256,bytes32)": TypedContractEvent<
      ReputationIncrementedEvent.InputTuple,
      ReputationIncrementedEvent.OutputTuple,
      ReputationIncrementedEvent.OutputObject
    >;
    ReputationIncremented: TypedContractEvent<
      ReputationIncrementedEvent.InputTuple,
      ReputationIncrementedEvent.OutputTuple,
      ReputationIncrementedEvent.OutputObject
    >;
  };
}
