/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AtomicSwap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AtomicSwap__factory>;
    getContractFactory(
      name: "IERC8004Reputation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC8004Reputation__factory>;
    getContractFactory(
      name: "IHTSPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHTSPrecompile__factory>;
    getContractFactory(
      name: "ERC8004Registry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC8004Registry__factory>;
    getContractFactory(
      name: "MockHTS",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHTS__factory>;

    getContractAt(
      name: "AtomicSwap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AtomicSwap>;
    getContractAt(
      name: "IERC8004Reputation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC8004Reputation>;
    getContractAt(
      name: "IHTSPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHTSPrecompile>;
    getContractAt(
      name: "ERC8004Registry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC8004Registry>;
    getContractAt(
      name: "MockHTS",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHTS>;

    deployContract(
      name: "AtomicSwap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AtomicSwap>;
    deployContract(
      name: "IERC8004Reputation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC8004Reputation>;
    deployContract(
      name: "IHTSPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHTSPrecompile>;
    deployContract(
      name: "ERC8004Registry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC8004Registry>;
    deployContract(
      name: "MockHTS",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHTS>;

    deployContract(
      name: "AtomicSwap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AtomicSwap>;
    deployContract(
      name: "IERC8004Reputation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC8004Reputation>;
    deployContract(
      name: "IHTSPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHTSPrecompile>;
    deployContract(
      name: "ERC8004Registry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC8004Registry>;
    deployContract(
      name: "MockHTS",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHTS>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
