/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AtomicSwap {
  export type TradeStruct = {
    marketAgent: AddressLike;
    user: AddressLike;
    htsToken: AddressLike;
    tokenAmount: BigNumberish;
    hbarAmountTinybars: BigNumberish;
    deadline: BigNumberish;
    state: BigNumberish;
  };

  export type TradeStructOutput = [
    marketAgent: string,
    user: string,
    htsToken: string,
    tokenAmount: bigint,
    hbarAmountTinybars: bigint,
    deadline: bigint,
    state: bigint
  ] & {
    marketAgent: string;
    user: string;
    htsToken: string;
    tokenAmount: bigint;
    hbarAmountTinybars: bigint;
    deadline: bigint;
    state: bigint;
  };
}

export interface AtomicSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTrade"
      | "executeTrade"
      | "getTrade"
      | "initiateTrade"
      | "reputationRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TradeCancelled"
      | "TradeExecuted"
      | "TradeInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTrade", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "initiateTrade",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistry",
    data: BytesLike
  ): Result;
}

export namespace TradeCancelledEvent {
  export type InputTuple = [tradeId: BytesLike, cancelledBy: AddressLike];
  export type OutputTuple = [tradeId: string, cancelledBy: string];
  export interface OutputObject {
    tradeId: string;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    tradeId: BytesLike,
    marketAgent: AddressLike,
    user: AddressLike,
    settlementNote: string
  ];
  export type OutputTuple = [
    tradeId: string,
    marketAgent: string,
    user: string,
    settlementNote: string
  ];
  export interface OutputObject {
    tradeId: string;
    marketAgent: string;
    user: string;
    settlementNote: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeInitiatedEvent {
  export type InputTuple = [
    tradeId: BytesLike,
    marketAgent: AddressLike,
    user: AddressLike,
    htsToken: AddressLike,
    tokenAmount: BigNumberish,
    hbarAmountTinybars: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: string,
    marketAgent: string,
    user: string,
    htsToken: string,
    tokenAmount: bigint,
    hbarAmountTinybars: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    tradeId: string;
    marketAgent: string;
    user: string;
    htsToken: string;
    tokenAmount: bigint;
    hbarAmountTinybars: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AtomicSwap extends BaseContract {
  connect(runner?: ContractRunner | null): AtomicSwap;
  waitForDeployment(): Promise<this>;

  interface: AtomicSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTrade: TypedContractMethod<[tradeId: BytesLike], [void], "nonpayable">;

  executeTrade: TypedContractMethod<[tradeId: BytesLike], [void], "nonpayable">;

  getTrade: TypedContractMethod<
    [tradeId: BytesLike],
    [AtomicSwap.TradeStructOutput],
    "view"
  >;

  initiateTrade: TypedContractMethod<
    [
      tradeId: BytesLike,
      user: AddressLike,
      htsToken: AddressLike,
      tokenAmount: BigNumberish,
      hbarAmountTinybars: BigNumberish,
      ttlSeconds: BigNumberish
    ],
    [void],
    "payable"
  >;

  reputationRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTrade"
  ): TypedContractMethod<[tradeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTrade"
  ): TypedContractMethod<[tradeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTrade"
  ): TypedContractMethod<
    [tradeId: BytesLike],
    [AtomicSwap.TradeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTrade"
  ): TypedContractMethod<
    [
      tradeId: BytesLike,
      user: AddressLike,
      htsToken: AddressLike,
      tokenAmount: BigNumberish,
      hbarAmountTinybars: BigNumberish,
      ttlSeconds: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "reputationRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TradeCancelled"
  ): TypedContractEvent<
    TradeCancelledEvent.InputTuple,
    TradeCancelledEvent.OutputTuple,
    TradeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TradeExecuted"
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TradeInitiated"
  ): TypedContractEvent<
    TradeInitiatedEvent.InputTuple,
    TradeInitiatedEvent.OutputTuple,
    TradeInitiatedEvent.OutputObject
  >;

  filters: {
    "TradeCancelled(bytes32,address)": TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;
    TradeCancelled: TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;

    "TradeExecuted(bytes32,address,address,string)": TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;

    "TradeInitiated(bytes32,address,address,address,int64,uint256,uint256)": TypedContractEvent<
      TradeInitiatedEvent.InputTuple,
      TradeInitiatedEvent.OutputTuple,
      TradeInitiatedEvent.OutputObject
    >;
    TradeInitiated: TypedContractEvent<
      TradeInitiatedEvent.InputTuple,
      TradeInitiatedEvent.OutputTuple,
      TradeInitiatedEvent.OutputObject
    >;
  };
}
