/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC8004Reputation,
  IERC8004ReputationInterface,
} from "../../AtomicSwap.sol/IERC8004Reputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "delta",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "tradeRef",
        type: "bytes32",
      },
    ],
    name: "incrementReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC8004Reputation__factory {
  static readonly abi = _abi;
  static createInterface(): IERC8004ReputationInterface {
    return new Interface(_abi) as IERC8004ReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC8004Reputation {
    return new Contract(address, _abi, runner) as unknown as IERC8004Reputation;
  }
}
