/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHTSPrecompile,
  IHTSPrecompileInterface,
} from "../../AtomicSwap.sol/IHTSPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "associateToken",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "int64",
        name: "amount",
        type: "int64",
      },
    ],
    name: "transferToken",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHTSPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IHTSPrecompileInterface {
    return new Interface(_abi) as IHTSPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHTSPrecompile {
    return new Contract(address, _abi, runner) as unknown as IHTSPrecompile;
  }
}
